version: '2'
services:
  db:
    image: mysql:8.0 # 8.0.42
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PSCh4ng3me!
      MYSQL_DATABASE: splinterstice_production
      MYSQL_USER: webuser
      MYSQL_PASSWORD: PSCh4ng3me!
    ports:
      - "3306:3306"
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - "./splinterstice:/app"
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_PASSWORD: PSCh4ng3me!
      DB_NAME: splinterstice_production
      DB_HOST: db

